### ISSUE TITLE
Coterie/ Period connection

### ISSUE THREAD

**Issue by angelawachowich** [sfu-dhil/mvm#107]
Can we add Periods to Coteries?

**Comment by angelawachowich** [comment]
This seems to have been done. One question though @schellenb would you like the Region to display on each card on the Coteries list, or just when you open a particular Coterie?

**Comment by schellenb** [comment]
Are you confusing period with region here, Angela? I don't see Period on the editing options for any Coterie, or on the display. As for the question re: display of Region on each card, I lean toward not having it, because: 1) the description already includes mention of the region in some form, even if not completely standardized reference to the county in every case; and 2) the coterie cards are already quite lengthy.

**Comment by angelawachowich** [comment]
Yes, you're right, never mind me!

**Comment by ubermichael** [comment]
It is very difficult to respond to a one-line feature request @angelawachowich. Please include more details in your bug reports or feature requests. It's best to use the templates we provide.

- Will period be required for coterie?
- Will coteries span multiple periods?
- Do you need a count of the coteries on the periods list, like the manuscripts count?
- Do you need see a list of coteries by period?

**Comment by schellenb** [comment]
Hi Michael, here's my stab at your 4 questions:
- yes, we would like to be able to enter period as a field when we edit/create a coterie entry
- yes, a coterie might span 2 periods; more than two would be highly unlikely
- it would be useful to have a count of coteries on the periods list
- again, it would be useful to be able to see a list of coteries by period, though I guess this would make the linking to further information from the periods list more complicated.
