### ISSUE TITLE
Aesop's Fables in Print Sources list

### ISSUE THREAD

**Issue by schellenb** [sfu-dhil/mvm#122]
Angela is not able to delete this source - she constantly gets an error message. What should happen is that she is able to delete it. We have asked about this a couple of times, so it is possibly a bug that doesn't want to be fixed.

**Comment by rcastong** [comment]
@angelawachowich ; Can you provide more details? We are unable to reproduce the bug systematically without more details. When you fill a bug report make sure you follow the guidelines:

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. The error is '....'

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Additional context**
Add any other context about the problem here.

**Comment by angelawachowich** [comment]
@ubermichael @rcastong 
Description: I can't delete Aesop's Fables from Print Sources.

To Reproduce: 
1. Go to Print Sources
2. Click on Aesop's Fables
3. Click Delete
4. The Error is Class: 500 - Doctrine\DBAL\Exception\ForeignKeyConstraintViolationException
Message: An exception occurred while executing 'DELETE FROM print_source WHERE id = ?' with params [6]: SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`mvm`.`manuscript_content`, CONSTRAINT `FK_D956C594E75A3578` FOREIGN KEY (`print_source_id`) REFERENCES `print_source` (`id`))

Expected behaviour: For Aesop's Fables to be deleted.

Screenshot attached:
<img width="1165" alt="Screenshot 2021-04-14 at 12 16 20 PM" src="https://user-images.githubusercontent.com/67483719/114766786-b158d980-9d1b-11eb-8567-0e20f8b39dcb.png">

**Comment by ubermichael** [comment]
You should be able to delete print sources now. If it doesn't work, or if you find other things you need to delete and can't, please create a new bug report.
