### ISSUE TITLE
Adjustment to Print Sources description under search ribbon

### ISSUE THREAD

**Issue by schellenb** [sfu-dhil/mvm#123]
Currently the Print Sources search line has the description: "Periodical, newspaper, miscellany, or anthology sources identified in at least one manuscript." Please change "identified" to "named." This may seem minor, but it is intended to make more clear the fact that we are using only named sources, not ones that we ourselves might identify.

**Comment by rcastong** [comment]
@schellenb ; Hi, Betty! We'll proceed to fix this but please next time make sure to follow the issue reporting template. I know the questions might seem tedious but they do help both developers doing their work. 

I think in this case you filed a "feature request", so the questions are as follows:

**Is your feature request related to a problem?

Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

**Describe the solution you'd like**
A clear and concise description of what you want to happen. Add any considered drawbacks.

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've considered.

**User Information**
If you can, explain how a user on the site will use this feature. What will they
expect to accomplish with this feature?

**Additional context**
Add any other context or screenshots about the feature request here.

**Comment by schellenb** [comment]
Thank-you for the feedback and update. Betty.
