### ISSUE TITLE
Determine display for Coteries

### ISSUE THREAD

**Issue by joeytakeda** [sfu-dhil/mvm#73]
(This ticket is mostly a broad overview of what needs to be done with the UI/UX for coteries; once we have made some decisions, this issue can be split into smaller and more actionable tickets.)

Coteries were recently added to the database and there is now enough data to start figuring out how best to display them on the site.

There's a few things that will need to be done just as a matter of course to match the look and feel of the site:

* Adding breadcrumb menu to the coteries page
* Changing the table display from hoverable/bordered to the more open grid
* Adding the search bar to the browse page rather than as a separate button

But we'll also need to think about what we want the coteries (and their associated pages) to contain. Coteries are fairly simple in terms of data structure—they may have a prose description and are associated with some number of people (and, as per #72, may have an associated region). So, at minimum, the coteries should display that information, but we'll need to think about what will most useful. Some thoughts:

* Do we want a simple list of those people or would it be helpful to have more information about each person on the coterie page?
* In what order should we display those people?
* Are there other relationships implied by the coterie-->person relationship that we ought to surface? I.e. since coteries are connected to people who are connected to manuscripts, there is an implied relationship between coteries and manuscripts, but we'll need to think carefully about what sorts of relationships are important and how they can be meaningfully represented. This isn't necessarily something that has to happen right off the bat, but it will be good to outline what sort of work we want those coterie pages to do, if any. 

In terms of people, each person currently has a link to their associated coteries. Some thoughts about that:

* Should it be a straight link or should it be a link and also list all of the other names of people in that coterie? I.e. should the page for William Linley list all of the other members of the Tickell Family coterie

> * Coteries:  Tickell Family
    * _Richard Brinsley Sheridan_
    * _Elizabeth Ann Sheridan_
    * _Richard Tickell_
    * _[M. Tickell]_
    * _Mary Linley_

* Do we envision that people are going to be in more than one coterie and, if so, is there some sort of special way we want to handle that? I.e. if Richard, Elizabeth, and Mary are part of Coterie A, and Richard, Mary, and Phillip are in Coterie B, should Richard's page emphasize in some way that he and Mary are in two coteries?

**Comment by angelawachowich** [comment]
In terms of the "need input" bits, there's a lot here that would be easier to clarify in a meeting rather than over github/ email. Perhaps we can arrange this? @schellenb

**Comment by joeytakeda** [comment]
Agreed--I was using this ticket just to keep my thoughts in order, which is a bit of an abuse of the system :-) I'll email to set something up.

**Comment by schellenb** [comment]
In fact, the points you raise, Joey, are ones Angela and I have been discussing and/or that I have been noting as I worked on coterie descriptions today, so we would probably be ready for this meeting anytime after Wednesday afternoon.

Best,
Betty

**Comment by joeytakeda** [comment]
Re-opening this issue since #80 does address some of the consistency bits, but we still need to determine the actual page layout / how coteries should be integrated into other pages etc.

**Comment by ubermichael** [comment]
My bad. I overzealously tagged this issue.

**Comment by schellenb** [comment]
Here is the outcome of my meeting with Angela (can't seem to make the bold function work when I cut and paste text, so will again add my name before each reply:
•	Do we want a simple list of those people or would it be helpful to have more information about each person on the coterie page? 
Betty: Simple listing of people is ok on this page – could click and find out more about the people if necessary
•	In what order should we display those people? 
Betty: Alphabetical by surname
•	Are there other relationships implied by the coterie-->person relationship that we ought to surface? I.e. since coteries are connected to people who are connected to manuscripts, there is an implied relationship between coteries and manuscripts, but we'll need to think carefully about what sorts of relationships are important and how they can be meaningfully represented. This isn't necessarily something that has to happen right off the bat, but it will be good to outline what sort of work we want those coterie pages to do, if any.
Betty: Not sure we fully understand the implications of this question. If about the person’s relationship to the coterie/manuscript, this should be covered by Manuscript Roles (e.g. primary compiler); the description of the coterie normally also gives an idea of who was at the centre, etc.

•	One more point from Betty: Would it also be complicated to add period to the coteries display? This is less informative than region, but could still potentially be useful for research. We realize this would mean we would have to enter standardized period designations for these groups, but this would be relatively simple to do, since the standardized periods already exist.
