### ISSUE TITLE
display of miscellany titles in tiles

### ISSUE THREAD

**Issue by schellenb** [sfu-dhil/mvm#90]
Hi. Where no title is given by the manuscript itself, we were using "Poetry Miscellany" and ticking the untitled box. This was supposed to make the placeholder title "Poetry Miscellany" appear in square brackets. However, untitled mss are showing on the tile display as having the title Poetry Miscellany, with no square brackets. Once you click on the ms for details, you see that it is untitled, although the placeholder title is still given. Can this be fixed so that the untitled box results in a square bracket around the title?

**Comment by joeytakeda** [comment]
Yep! That's a simple fix. One question, though: if we're putting square brackets around it, do we need to show the "Untitled" row in the MSS page or can we just delete it?

 I.e. instead of having the title, the untitled Yes/No, and then the Archive like this:

![Screen Shot 2021-01-19 at 3 16 05 PM](https://user-images.githubusercontent.com/17664763/105105613-4627a000-5a69-11eb-9a5b-59c778218083.png)

Can we just have Title and Archive if we add the square brackets?

![Screen Shot 2021-01-19 at 3 13 43 PM](https://user-images.githubusercontent.com/17664763/105105775-9ef73880-5a69-11eb-8865-bff7d3d6ca06.png)

**Comment by schellenb** [comment]
Hi Joey, it was in fact our original understanding that the square brackets would appear by magic around the catalogue “title” when we ticked a box indicating that the ms was untitled. Since that doesn’t seem to be the case, we can go back in a put the square brackets in manually and once that is done you can delete the “untitled” line.

Thanks. Betty.

Betty A. Schellenberg, PhD, FRHistS
Professor of English
Simon Fraser University
Burnaby BC Canada
V5A 1S6
schellen@sfu.ca
778-782-3136
www.cambridge.org/9781107128163<http://www.cambridge.org/9781107128163>

**Comment by joeytakeda** [comment]
There's no need to change any data, since this can be done automatically on the front-end--I'll programatically add the brackets around all of the untitled titles, and remove the Untitled row from the display

**Comment by schellenb** [comment]
Ok, that’s good to know, Joey, thanks. Betty.

**Comment by schellenb** [comment]
Very happy with this fix, thanks. Betty.
