### ISSUE TITLE
Manuscript search issues

### ISSUE THREAD

**Issue by angelawachowich** [sfu-dhil/mvm#99]
Hi Michael,

As Betty and I understand it, the manuscript search field should turn up results for call numbers and titles. We think there is an issue with the call number search though. Here are two examples of the problem:
1. If I am looking for "Folger MS M.a. 15" I can't get results by searching "MS M.a. 15," "M.a. 15," or "15," and if I search "Folger MS M.a. 15," I am shown all the Folger manuscripts.
2. If I'm looking for Beinecke Osborn c130, I can only find it by searching "c130" (an incorrect result when I search "c 130," "130," or "c.130"). If I include the word "Osborn" or "Beinecke Osborn," I am shown all the Beinecke manuscripts.

Can the manuscript search field be made less space/ punctuation sensitive, and can it be refined so that when you include the archive name in the call number, you aren't shown all manuscripts from that archive?

**Comment by ubermichael** [comment]
The problem is caused by the very short "words" in the manuscript names. MS and M.a. and 15 are too short for the text indexing algorithms and they get confused by it.

I can adjust the search code for manuscripts so that it does exact string matching instead. So if you search for 15 you will see results the results you expect (and also matches for 150 and 215 etc). Does that seem like a good solution?

**Comment by ubermichael** [comment]
I think I have a solution that should work.

If you quote the search term ("m.a." or "c130") it will do an exact search and find manuscripts with call numbers that include the quoted term. If you leave out the quotes the search works as before, searching the call number and the description fields.

Can you give it a try and see if it meets your needs?

**Comment by angelawachowich** [comment]
I'm a little confused. Why can I search short "words" and get results from some archives (eg Leeds Brotherton) and not others (eg Folger, Beinecke)? 

Could we adjust the search codes? Searching in quotations is great if you know the exact call number (meaning the proper punctuation and spacing as we have recorded them), but it would be nice to have a backup for users who don't.

**Comment by ubermichael** [comment]
I think it's time to talk about searching in a bit more detail. What would a user who isn't sure of a call number search for? What would they expect to find?

Adjusting the search isn't a quick or simple or easy thing.

**Comment by ubermichael** [comment]
Also, can you provide more specific, repeatable examples of "Why can I search short "words" and get results from some archives (eg Leeds Brotherton) and not others (eg Folger, Beinecke)?" Without something I can try on my own there isn't much I can do to try to figure out what is going on.

**Comment by schellenb** [comment]
Hi all. Just to respond to some of the issues here:

- the exact search option for call numbers seems to me to be the best solution. It requires adjusting to spacing and punctuation issues, but this is how it works with the FLI and library catalogue searches as well - frustrating, but ultimately navigable. One thing we can consider on our end is standardizing our punctuation and spacing use for call nos., at least to a degree, and also writing a brief instruction under the search line that would help with this.

- understood that searches with only 2 digits or letters (e.g. 15) just aren't going to work. 

- but for the question of short sequences pulling some results and not others - here are a few examples:
1. if I search 119 (without qtn marks), I get Folger MS W.a. 119, but not Leeds Brotherton Lt119. Is this because the algorithm looks for a sequence with blank spaces around it? But if I search "119," I get both results.
2. a similar example: 110 produces Folger MS M.a. 110, but not Beinecke Osborn c110 or Leeds Brotherton Lt110, both of which are added in when I do "110"
3. if I search 157, I get no results at all, presumably because nothing at the Folger has that call number, but "157" does produce Osborn c157.

**Comment by schellenb** [comment]
with regard to what a user not knowing a call number might search for, my hunch is:

- archive
- name associated with a manuscript - e.g. I want to know if there are any Burney family mss here; or: how many mss in this database are anonymous?
- possibly a title keyword
- period
- what they **won't ** do is search for a specific number in the description - e.g. is there any collection with 110 items in it?  So specific number searches are likely to be searches for call numbers (or periods, which would take the form of 1701-1730, for example). But the fact that unsought results like the number "110" from a description will show up in a call no. search is just the way of searches, I think. I've thought about removing description from the manuscript search field, but I don't think that would be desirable.
